import type { Metadata } from 'next';
import { Geist, Geist_Mono, Poppins } from 'next/font/google';
import './globals.css';
import React, { Suspense } from 'react';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-poppins',
});

export const metadata: Metadata = {
    title: 'PhiliPC - E-Commerce for Computers',
    description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({
    children,
}: Readonly<{ children: React.ReactNode }>) => {
    return (
        <html
            lang="en"
            className={`${poppins.variable} scrollable`}
        >
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} ansialiased`}
            >
                <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
            </body>
        </html>
    );
};

export default RootLayout;
